### ISSUE TITLE
Create a logo for this repo

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/hacktoberfest-2023-participants#2]
Use OSSPH's logo from the [press kit](https://drive.google.com/drive/u/2/folders/1uVuUZmfQrIh-vs17rK5soPS05wuS4vkQ) and Hacktober Fest 2022's logo. 

Idea: 

OSSPH + Hacktobefest 2022

**Comment by chaaals** [comment]
> Use OSSPH's logo from the [press kit](https://drive.google.com/drive/u/2/folders/1uVuUZmfQrIh-vs17rK5soPS05wuS4vkQ) and Hacktober Fest 2022's logo.
> 
> Idea:
> 
> OSSPH + Hacktobefest 2022

Hi kuya @jofftiquez , I think I could help with this one!

**Comment by 12-malak** [comment]
@jofftiquez Hi, I would like to work on this issue. Please assign me.

**Comment by 12-malak** [comment]
@jofftiquez Created PR #8. Please review and merge. Also, please feel free to add the hacktoberfest-accepted label once approved.
